### ISSUE TITLE
Provide a setter for the circuit room temperature

### ISSUE THREAD

**Issue by lu-zero** [LavermanJJ/home-assistant-solarfocus#108]
The circuit room temperature would be nice to be able to set it from other HA sensors instead of just reading it if it is otherwise set.

**Comment by LavermanJJ** [comment]
As a workaround you could utilize the Modbus integration and an automation. 

You need a o replace the sensors the values are taken from.

```
alias: Solarfocus - Publish inside temperature and -humidity
description: ""
trigger:
  - platform: time_pattern
    minutes: "*"
condition: []
action:
  - service: modbus.write_register
    data_template:
      unit: 255
      value: "[{{ (states('sensor.inside_temperature')|float * 10) | int}}]"
      hub: solarfocus
      address: 32606
  - service: modbus.write_register
    data_template:
      unit: 255
      value: "[{{ states('sensor.inside_humidity') | int }}]"
      hub: solarfocus
      address: 32607
mode: single

```

And the modbus configuration:

```

---
modbus:
  - name: solarfocus
    type: tcp
    host: <ip-address>
    port: 502

    sensors:
# you need to include at least one sensor for the Modbus integration to work
      - name: waermepumpe.status
        slave: 1
        address: 2330
        input_type: input
        data_type: int16
        scan_interval: 0
 

```
