### ISSUE TITLE
How to send PV sensor data from Deye Inverters to Solarfocus via modbus

### ISSUE THREAD

**Issue by ich-andy** [LavermanJJ/home-assistant-solarfocus#111]
Hello, 
I'm running your Modbus Integration successful (many thanks for your work). 
Now I would like to send my PV data to solarfocus to use the PV Overcharge option of the heatpump. 
As I have no clue about modbus, so may I ask for some guidance? 
How can I send the data of "sensor.deye_grid_export" (this is my sensor measuring the overcharge of my PV system) via modbus to register 2508 of the heatpump.
Sorry for bothering you/the community.

Thanks a lot,
Andreas

**Comment by Vaszago** [comment]
@ich-andy 
I have a solaredge inverter and was able to connect it to the heat pump. I also have a description of how to set it up. Maybe your Deye inverter is also supported. If you have any further questions, please feel free to contact me.
[vampair_PV-Eigenverbrauchsoptimierung_Anleitung.pdf](https://github.com/user-attachments/files/16751774/vampair_PV-Eigenverbrauchsoptimierung_Anleitung.pdf)

**Comment by ich-andy** [comment]
Hello Vaszago,
many thanks and my apologize for late reply!

I guess my problem is more on the HA side (my fault because I’m not experienced enough with Modbus)
I can read out all data from the vampair and also can manually make changes to it via the solar focus integration.
What does not work is the HA automation to load the PV data into the vampair registers so the vampair “knows” my pv and grid values.

**Comment by LavermanJJ** [comment]
Please see my config below. 
* grid_exported_power: Sensor for power exported to the grid
* grid_imported_power: Sensor for power imported from grid
* pv-power-sensor: Sensor for PV generated power

```
alias: Solarfocus - Publish Photovoltaik
description: "Publish PV converter to Solarfocus"
trigger:
  - platform: state
    entity_id:
      - sensor.<pv-power-sensor>
condition:
  - condition: numeric_state
    entity_id: sensor.<pv-power-sensor>
    above: "0"
action:
  - data_template:
      unit: 255
      value: "[{{ states('sensor.<pv-power-sensor>') | int(default=0) }}]"
      hub: solarfocus
      address: 33408
    action: modbus.write_register
  - if:
      - condition: numeric_state
        entity_id: sensor.<grid_imported_power>
        above: "0"
    then:
      - data_template:
          unit: 255
          value: "[-{{ states('sensor.<grid_imported_power>') | int(default=0) }}]"
          hub: solarfocus
          address: 33407
        action: modbus.write_register
    else:
      - data_template:
          unit: 255
          value: "[{{ states('sensor.<grid_exported_power>') | int(default=0) }}]"
          hub: solarfocus
          address: 33407
        action: modbus.write_register
mode: single
```
